apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base/default-ocpstorageclass.yaml
  - base/gitops-cp-ban-operator-cp4ba-operator.yaml
  - base/namespace-gitops-cp-ban-operator.yaml
  - base/openshift-marketplace-ibm-catalogs.yaml
  - base/openshift-marketplace-ibm-entitlement-key.yaml
