apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: default-ocpstorageclass
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/default/ocpstorageclass
    repoURL: https://github.com/cloud-native-toolkit-test/gitops-cp-ban-operator
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
