apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-cp-ban-operator-cp4ba-operator
spec:
  destination:
    namespace: gitops-cp-ban-operator
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/gitops-cp-ban-operator/cp4ba-operator
    repoURL: https://github.com/cloud-native-toolkit-test/gitops-cp-ban-operator
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
